profile: sit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:876/
  instance:
    hostname: localhost

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

