signing-key: 2cec40f81d0ef7304b93bf653a54680f
profile: sit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.9:8761/eureka/
swagger:
  enable: true
spring:
  zipkin:
    base-url: http://192.168.1.8:9411/
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    redis:
      database: 0
      port: 6379
      host: 192.168.1.8
      password: