profile: sit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
swagger:
  enable: true
spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    username: maker
    password: maker
    port: 15672
    exchange:
      direct:
        name: saga.pattern.direct.sit
        durability: true
        auto-delete: false
      topic:
        name: saga.pattern.topic.sit
        durability: true
        auto-delete: false
      fanout:
        name: saga.pattern.fanout.sit
        durability: true
        auto-delete: false
    queue:
      direct:
        name: saga.pattern.direct.sit
        durability: true
        auto-delete: false
      topic:
        name: saga.pattern.topic.department.sit
        durability: true
        auto-delete: false
      fanout:
        name: saga.pattern.fanout.department.sit
        durability: true
        auto-delete: false
    routingKey:
      direct: saga.pattern.direct.department
      topic: saga.pattern.service.*
    virtualHost: /saga