profile: sit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
swagger:
  enable: true
spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 15672
    virtualHost: /saga