profile: sit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.9:8761/eureka/
swagger:
  enable: true
spring:
  zipkin:
    base-url: http://192.168.1.8:9411/
  rabbitmq:
    host: 192.168.1.8
    username: admin
    password: admin
    port: 15672
    virtualHost: /saga